### ISSUE TITLE
how to general _xy_positions.log file in ours dataset

### ISSUE THREAD

**Issue by 18150167970** [val-iisc/css-ccnn#1]
I don't find code to generate xxxxx_xy_positions.log. How to generate xxxxx_xy_positions.log file in ours dataset?

**Comment by abhinavagarwalla** [comment]
Hi 

Thank you for your interest.

The code to generate xy_positions.log is inside `crowd_dataset.py`. The file can be very easily generated with small changes:

1. Line 119: needs to be modified to open the file in write mode.
`self.val_pos = open('resources/{}_xy_positions.log'.format(name), 'w')`
2. Line 239: to be set True.

That should do it.
